In [9]:
import numpy as np

In [10]:
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.matmul(x, W1) + b1

In [11]:
W1

array([[ 0.97850524, -0.04571622,  0.45827938, -1.55131476],
       [ 0.8112674 ,  0.79128064, -1.60385526, -1.47902611]])

In [12]:
b1

array([ 0.981905  ,  1.04962333, -0.26822245, -1.5200055 ])

In [13]:
x

array([[-1.53854443e+00,  8.20683073e-01],
       [-1.49103269e+00,  2.87116527e-01],
       [-8.25966733e-01,  1.40471296e+00],
       [-3.81412132e-01,  1.17362177e-03],
       [ 2.64054183e-01,  1.32314725e+00],
       [ 8.41322542e-01,  2.80991749e-02],
       [-1.26406141e+00, -1.00460061e+00],
       [ 4.78258287e-01,  5.80857751e-01],
       [ 1.59426756e+00,  4.08678782e-01],
       [-5.34612361e-01, -1.28127315e+00]])

In [14]:
h

array([[ 0.14222463,  1.76935039, -2.2895625 , -0.34705052],
       [-0.24415003,  1.34497746, -1.41202534,  0.36840268],
       [ 1.31329005,  2.19890557, -2.89970224, -2.31627826],
       [ 0.60964335,  1.06798871, -0.44489809, -0.93005105],
       [ 2.31370963,  2.08453257, -2.26934855, -3.88660598],
       [ 1.82793946,  1.03339557,  0.07227131, -2.86672099],
       [-1.06998544,  0.31249043,  0.76371824,  1.92678213],
       [ 1.9211142 ,  1.48738066, -0.9806583 , -3.12103842],
       [ 2.87345193,  1.30011905, -0.19306412, -4.59766288],
       [-0.58067114,  0.06021715,  1.54175242,  1.20438299]])